/**
 * firmware_export.h — GENERATED by export_policy_c.py from runs/traj_lissajous/ppo_body_yawpen.
 * Do not edit by hand; re-run the exporter instead.
 *
 * Every constant examples/app_nnpol needs beyond the network itself. The
 * hash words are this policy's identity: sha256 (truncated to 128 bits)
 * over the canonical identity record in firmware_export.json, exposed by
 * the app as read-only params nnpol.hash0-3 and checked by the ground
 * station before an `exec: onboard` engage. Full hash: 07e01165ae1dac63be20abfed61decee
 */
#ifndef FIRMWARE_EXPORT_H
#define FIRMWARE_EXPORT_H

#define NNPOL_TASK "traj_lissajous"
#define NNPOL_OBS_FN "body"
#define NNPOL_ACTION_TYPE "mellinger"

#define NNPOL_OBS_DIM 40
#define NNPOL_ACTION_DIM 4
#define NNPOL_CTRL_FREQ_HZ 100

#define NNPOL_HASH0 0x6511E007u
#define NNPOL_HASH1 0x63AC1DAEu
#define NNPOL_HASH2 0xFEAB20BEu
#define NNPOL_HASH3 0xEEEC1DD6u

// Action box (config.json mellinger_attitude_low/high): setpoint =
// mid + clip(action, -1, 1) * half, channels [roll, pitch, yaw, thrust]
// in rad/rad/rad/N. A property of the trained checkpoint — never recompute.
#define NNPOL_ACTION_LOW  { -1.57079637f, -1.57079637f, -1.57079637f, 0.0854505226f }
#define NNPOL_ACTION_HIGH { 1.57079637f, 1.57079637f, 1.57079637f, 0.800000012f }
#define NNPOL_ACTION_MID  { 0.0f, 0.0f, 0.0f, 0.442725271f }
#define NNPOL_ACTION_HALF { 1.57079637f, 1.57079637f, 1.57079637f, 0.357274741f }

// tasks/traj_lissajous reference curve and lookahead window:
//   ref(t) = [A sin(wt), 0, A/2 sin(2wt) + CENTER_Z],  w = 2 pi / T
// n_samples points spaced SAMPLES_DT apart, offsets starting at 0 (the
// current reference point is included).
#define NNPOL_T_PERIOD_S 10.0f
#define NNPOL_AMPLITUDE_M 1.0f
#define NNPOL_CENTER_Z_M 1.0f
#define NNPOL_N_SAMPLES 10
#define NNPOL_SAMPLES_DT_S 0.100000001f
// T/4: the body-frame variant's default engage phase (the ROS
// TrajLissajousBody.DEFAULT_START_PHASE) — the host pushes the actual
// value as nnpol.startPhase at engage, this is only the standalone default.
#define NNPOL_DEFAULT_START_PHASE_S 2.5f

// cf21B_500 thrust identification (crazyflow drones/params.toml), the
// inverse of which maps the policy's collective newtons to the legacy
// thrust setpoint: F/4 -(rpm2thrust solved)-> rpm -(vmotor2rpm)-> V ->
// pwm16 = 65535 * V / vnom, at the battery voltage pushed as nnpol.vnom.
#define NNPOL_RPM2THRUST_A0 0.0f
#define NNPOL_RPM2THRUST_A1 -3.13342724e-07f
#define NNPOL_RPM2THRUST_A2 4.40735476e-10f
#define NNPOL_VMOTOR2RPM_K0 2938.39966f
#define NNPOL_VMOTOR2RPM_K1 6001.83398f

#endif // FIRMWARE_EXPORT_H
