/**
 * policy.h — GENERATED by export_policy_c.py (--format const-fp32) from
 * runs/traj_lissajous/ppo_body_yawpen. Do not edit by hand; re-run the exporter instead.
 *
 * Actor-only forward pass (deterministic mean, no log_std/critic). Source
 * checkpoint: task='traj_lissajous' action_type='mellinger'
 * obs_fn='body' hidden=[128, 128] activation='tanh'
 *
 * Weights are `static const float` in policy.c — the linker places them in
 * flash (POLICY_TOTAL_FLOATS * 4 bytes), no RAM is used and there is no
 * runtime upload in this format: a new checkpoint is a reflash. The policy
 * identity is the four NNPOL_HASH words in firmware_export.h, exposed as
 * read-only params by the app and checked by the ground station.
 */
#ifndef POLICY_H
#define POLICY_H

#include <stdint.h>

#define POLICY_OBS_DIM 40
#define POLICY_ACTION_DIM 4
#define POLICY_NUM_LAYERS 3
#define POLICY_TOTAL_FLOATS 22276

/**
 * Deterministic actor forward pass: obs[POLICY_OBS_DIM] ->
 * actionOut[POLICY_ACTION_DIM]. actionOut is the raw (unsquashed) mean —
 * the caller must clip to [-1, 1] itself, matching training-time
 * env.step()'s own clip. No internal state; safe to call from a single
 * task. ~22276 MACs per call.
 */
void policyForward(const float obs[POLICY_OBS_DIM], float actionOut[POLICY_ACTION_DIM]);

#endif // POLICY_H
